version: '2'
checks:
  file-lines:
    enabled: false
    config:
      threshold: 250
  method-lines:
    enabled: true
    config:
      threshold: 60
  similar-code:
    enabled: true
    config:
      threshold: 70
  identical-code:
    enabled: true
    config:
      threshold: 70
  duplication:
    enabled: true
exclude_patterns:
  - '.circleci/'
  - '.github/'
  - '**/src/mocks/'
  - '**/scripts/'
  - '**/apps/'
  - '**/api-specifications/'
  - '**/core/'
  - '**/*.d.ts'
  - '**/src/const/*.ts'
  - tests/
  - test/
  - 'spec/'
